/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.esempe.kafkaclient;

import java.io.IOException;
import java.util.Collections;
import java.util.Properties;
import java.util.concurrent.ExecutionException;

import org.apache.kafka.clients.admin.KafkaAdminClient;
import org.apache.kafka.clients.producer.Callback;
import org.apache.kafka.clients.producer.KafkaProducer;
import org.apache.kafka.clients.producer.ProducerConfig;
import org.apache.kafka.clients.producer.ProducerRecord;
import org.apache.kafka.clients.producer.RecordMetadata;

public class App {
	public static void main(String[] args) throws IOException, InterruptedException, ExecutionException 
	{
		System.out.println("Hello Kafka 3.0.0 world!");
		
		// "Liste" aller Bootstrap-Server <Hostname>:<Ports> z.B "R9118:9092;R9118:9093;R9118:9094"
		var bootstrapServer = "[::1]:9092";
		var admin = new Admin(bootstrapServer);
		admin.describeTopics();
		
		var producer = new Producer(bootstrapServer);
		producer.produceMsg("demo", "4711", "Eva Mustermann");
		producer.produceMsg("demo", "4812", "Anton Mustermann");
						
		System.out.println("Bye!");

	}
}
